[project]
name = "CalibDBReader"
version = "1.0.3"
description="Reader for the calibration database"
dependencies = [

    'importlib-metadata',

    "gitpython (>=3.1.45,<4.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "numpy (>=2.3.4,<3.0.0)",
    "semantic-version-tools (>=1.4.1,<2.0.0)",
    "rich (>=15.0.0,<16.0.0)",
    "myxmltools (>=0.2.0,<0.3.0)",
]

authors = [{name="Romolo Politi", email ="Romolo.Politi@inaf.it" }]
license = {text = "GNU GPL ver3"} 
readme = "README.md"
requires-python = ">= 3.14, <4.0"


keywords = ["Space Mission", "BepiColombo", "SIMBIO_SYS", "Calibration Database", "JUICE", "JANUS"]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]

[project.urls]
Repository = "https://github.com/RomoloPoliti-INAF/Calib_DB_Reader"
Changelog = "https://github.com/RomoloPoliti-INAF/Calib_DB_Reader/CHANGELOG.md"


[tool.poetry]
packages = [
    { include = "CalibDBReader", from = "src" },
]
# test =["pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"



[dependency-groups]
devel = [
    "ruff (>=0.15.19,<0.16.0)"
]

[tool.ruff.lint.isort]
known-first-party = ["CalibDBReader"]
combine-as-imports = true
lines-after-imports = 2